---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: blue95
description: A workstation from your childhood home's computer room

base-image: ghcr.io/ublue-os/base-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  # https://github.com/hyperreal64/vauxite-build/blob/main/src/xfce-desktop-pkgs.yaml
  - type: rpm-ostree
    install:
      - NetworkManager-openconnect-gnome
      - NetworkManager-openvpn-gnome
      - NetworkManager-pptp-gnome
      - NetworkManager-ssh-gnome
      - NetworkManager-vpnc-gnome
      - Thunar
      - adwaita-gtk2-theme
      - adwaita-icon-theme
      - blueman
      - firefox
      - galculator
      - gnome-keyring-pam
      - greybird-dark-theme
      - greybird-light-theme
      - greybird-xfce4-notifyd-theme
      - greybird-xfwm4-theme
      - gtk-xfce-engine
      - gvfs
      - gvfs-archive
      - gvfs-mtp
      - initial-setup-gui
      - lightdm-gtk
      - mint-y-theme
      - mousepad
      - network-manager-applet
      - nm-connection-editor
      - ristretto
      - seahorse
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-volman
      - xarchiver
      - xdg-user-dirs-gtk
      - xfce4-about
      - xfce4-appfinder
      - xfce4-clipman-plugin
      - xfce4-datetime-plugin
      - xfce4-dict-plugin
      - xfce4-panel
      - xfce4-places-plugin
      - xfce4-power-manager
      - xfce4-pulseaudio-plugin
      - xfce4-screensaver
      - xfce4-screenshooter-plugin
      - xfce4-session
      - xfce4-settings
      - xfce4-taskmanager
      - xfce4-terminal
      - xfconf
      - xfdesktop
      - xfwm4
      - xfwm4-themes
      - zathura
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

