---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: blue95
description: A desktop for your childhood home's computer room

base-image: quay.io/fedora-ostree-desktops/xfce-atomic
image-version: 41

# module configuration, executed in order
modules:
  - type: files
    files:
      - source: system
        destination: /

    # Packages needed by the build scripts
  - type: rpm-ostree
    install:
      - plymouth-plugin-script

  - type: script
    scripts:
      - 02-defaults.sh
      - 03-ublue.sh
      - 10-install-appimages.sh
      - 20-chicago95.sh

  # General packages
  - type: rpm-ostree
    install:
      - neovim
      - btop
      - fastfetch
      - lightdm-gtk-greeter-settings
      - vorbis-tools
      - qt5-qtstyleplugins
      - libcanberra
      - sox
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished
    system:
      # Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.kde.kolourpaint

  # Regenerate initramfs because of plymouth
  - type: initramfs

  - type: signing

