---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: blue95
description: A desktop from your childhood home's computer room

base-image: quay.io/fedora-ostree-desktops/xfce-atomic
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - 02-defaults.sh
      - 10-install-appimages.sh
      - 20-chicago95.sh

  - type: rpm-ostree
    install:
      - neovim
      - just
      - btop
      - fastfetch
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
    user: {} # Also add Flathub user repo, but no user packages

  # Regenerate initramfs because of plymouth
  - type: initramfs
  - type: signing

